name: Build and Push

on:
  push:
    branches: ["main"]
    paths-ignore: ["deploy/**"]

env:
  IMAGE_NAME: srinivasraop03/gitops-service-c
  DEPLOYMENT_FILE: ./deploy/deployment.yaml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        # Set these secrets in your repo: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Deployment YAML
        if: github.event_name != 'pull_request'
        run: |
          NEW_TAG="${{ steps.meta.outputs.tags }}" 
          sed -i "s|image: .*|image: $NEW_TAG|g" $DEPLOYMENT_FILE

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add $DEPLOYMENT_FILE
          git commit -m "ci: update image tag [skip ci]"
          git push
